apiVersion: v1
kind: Secret
metadata:
  name: menufacil-api-java-secrets
  labels:
    app.kubernetes.io/name: menufacil-api-java
    app.kubernetes.io/part-of: menufacil
    {{- with .Values.secretEnvLabel }}
    env: {{ . }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
