apiVersion: v1
kind: Service
metadata:
  name: menufacil-api-java
  labels:
    {{- include "backend.metaLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
