apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: menufacil-api-java-hml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: menufacil
  source:
    repoURL: https://github.com/MaisTech/menufacil
    targetRevision: develop
    path: infra/charts/backend
    helm:
      valueFiles:
        - ../../apps/menufacil-api-java/values-hml.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: menufacil-hml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
