apiVersion: v1
kind: Secret
metadata:
  name: menufacil-secrets
  namespace: menufacil
type: Opaque
stringData:
  # Database
  DB_PASSWORD: "CHANGE_ME"
  # JWT
  JWT_SECRET: "CHANGE_ME"
  JWT_REFRESH_SECRET: "CHANGE_ME"
  # MinIO
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"
  # Stripe
  STRIPE_SECRET_KEY: "sk_test_xxx"
  STRIPE_WEBHOOK_SECRET: "whsec_xxx"
  # PIX
  PIX_CLIENT_ID: "xxx"
  PIX_CLIENT_SECRET: "xxx"
