import { createApi } from '@reduxjs/toolkit/query/react';
import { axiosBaseQuery } from './axiosBaseQuery';

export const baseApi = createApi({
  reducerPath: 'api',
  baseQuery: axiosBaseQuery,
  refetchOnFocus: true,
  refetchOnReconnect: true,
  tagTypes: [
    'Categories',
    'Products',
    'Orders',
    'Customers',
    'DeliveryZones',
    'Coupons',
    'Loyalty',
    'Tenant',
    'TenantPublic',
    'Settings',
    'Dashboard',
    'Profile',
    'Plan',
    'CustomerProfile',
    'CustomerOrders',
    'DeliveryPersons',
    'Staff',
    'Roles',
    'LoyaltyRewards',
    'LoyaltyRedemptions',
    'Tables',
    'TableSessions',
    'Reservations',
    'FloorPlans',
    'WhatsappStatus',
    'WhatsappTemplates',
    'WhatsappConversations',
    'WhatsappMessages',
    'WhatsappFlows',
    'Units',
    'ExtraGroups',
    'CashRegister',
    'Inventory',
    'Reviews',
    'ReviewStats',
    'AbandonedCarts',
    'AbandonedCartStats',
    'CustomerSegments',
    'LoyaltyTiers',
    'Referrals',
    'ReferralStats',
    'Analytics',
    'Promotions',
    'Wallet',
    'WalletTransactions',
  ],
  endpoints: () => ({}),
});
